version: '3'
volumes:
  mysql_data:
  vendor_bundle:
  storage:

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - .:/osusowake
      - /osusowake/log
      - /osusowake/tmp
      - vendor_bundle:/osusowake/vendor/bundle
      - storage:/osusowake/storage
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0

